GET http://localhost:3000/subscribers

###
GET http://localhost:3000/subscribers/62839c8613a012f1370755dc

###
POST http://localhost:3000/subscribers
Content-Type: application/json; charset=utf-8

{
    "name": "Dario Edgar Prazeres",
    "subscriberToChannel": "Dp Channel"
}
###
GET http://localhost:3000/subscribers/12

###
DELETE http://localhost:3000/subscribers/6282c8fcf83bbb31c34087a9

###
PATCH http://localhost:3000/subscribers/6282c8fcf83bbb31c34087a9
Content-Type: application/json; charset=utf-8

{
    "name": "Dario Edgar Prazeres"
}